apiVersion: v1
kind: Namespace
metadata:
  name: env0-agent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server-deployment
  namespace: env0-agent
spec:
  selector:
    matchLabels:
      app: echo-server
  replicas: 1
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
        - name: echo-server-container
          image: ghcr.io/env0/echo-http-server:latest
          ports:
            - containerPort: 3000
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server-service
  namespace: env0-agent
spec:
  type: LoadBalancer
  selector:
    app: echo-server
  ports:
    - name: http
      port: 80
      targetPort: 3000
